language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.7
# command to install dependencies
install: "pip install -r requirements.txt"
before_script: 
  - python manage.py makemigrations
  - python manage.py migrate
# command to run tests
script: python manage.py test
